### ISSUE TITLE
Stale branches: cc3d_hackathon_day1 and cc3d_hackathon_day2

### ISSUE THREAD

**Issue by tjsego** [covid-tissue-models/covid-tissue-response-models#62]
Is there any reason not to delete [cc3d_hackathon_day1](https://github.com/covid-tissue-models/covid-tissue-response-models/tree/cc3d_hackathon_day1) and [cc3d_hackathon_day2](https://github.com/covid-tissue-models/covid-tissue-response-models/tree/cc3d_hackaton_day2)?

**Comment by JulianoGianlupi** [comment]
day 2 has diffs to master, but they are prob outdated by now

**Comment by tjsego** [comment]
Looks like mostly tangential/outdated stuff in the diffs. I think it's OK to delete.

**Comment by JulianoGianlupi** [comment]
ok, deleted
