### ISSUE TITLE
Stale branch: Movies

### ISSUE THREAD

**Issue by tjsego** [covid-tissue-models/covid-tissue-response-models#64]
@joaponte if you'd still like to merge this, can you remove all pngs and issue a new PR with just the movies? Instead of including the pngs, you can upload them elsewhere and include a link here with the movies. 

Otherwise, I'd like to delete [Movies](https://github.com/covid-tissue-models/covid-tissue-response-models/tree/Movies).

**Comment by joaponte** [comment]
I think we can delete it entirely. At this point I don't even remember what all of this is about.

**Comment by tjsego** [comment]
Branch has been deleted.
