### ISSUE TITLE
What to do with feature/signal_generators?

### ISSUE THREAD

**Issue by tjsego** [covid-tissue-models/covid-tissue-response-models#65]
Dosing examples have been dropped from [feature/signal_generators](https://github.com/covid-tissue-models/covid-tissue-response-models/tree/feature/signal_generators) in favor of the ODE-based dosing model method being developed by @JulianoGianlupi. As such, [feature/signal_generators](https://github.com/covid-tissue-models/covid-tissue-response-models/tree/feature/signal_generators) now only consists of two signal generators (neither of which are used anywhere currently) and a home for future development of other signals. Is this worth merging for potential use in future work, or should we just delete this branch?

**Comment by JulianoGianlupi** [comment]
Let me give it a read and see if I can use something that's here

**Comment by tjsego** [comment]
Issue and associated branch are stale. Closing and deleting.
